version: "3"

services:
  vault:
    image: vault:latest
    volumes:
      - ./data/vault/config:/vault/config
      - ./data/vault/policies:/vault/policies
      - ./data/vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      # go cloud sdk
      #- VAULT_SERVER_TOKEN=s.HTMkPc6QoKmOzRE3CseOPBu1
      #- VAULT_SERVER_URL=http://127.0.0.1:8200

      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    #command: vault server -dev
